services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: baseTaller
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

  api:
    build:
      context: .
      dockerfile: ProductsService.API/Dockerfile
    ports:
      - "5279:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=baseTaller;Username=admin;Password=admin"
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - db
    restart: on-failure
volumes:
  pgdata:
